### ISSUE TITLE
Clean up `IndsNetwork` and `ITensorNetwork` constructors

### ISSUE THREAD

**Issue by mtfishman** [mtfishman/ITensorNetworks.jl#142]
The logic of `IndsNetwork` and `ITensorNetwork` constructors is pretty complicated right now, it could use a refactor to make it clearer where certain keyword arguments are being used, what information about the `IndsNetwork` is used by the `ITensorNetwork`, etc.

Related to #141.

**Comment by b-kloss** [comment]
Adding here that it would be nice to allow for passing a dictionary from `vertices` to `Strings` to specify an initial product state. Currently, the only (convenient) way to specify an initial state is as a function returning e.g. the operator string for each vertex input.

**Comment by mtfishman** [comment]
Closed by #155.
