### ISSUE TITLE
Rename_Vertices(g::NamedDimGraph, ...) does not work on an ITensorNetwork

### ISSUE THREAD

**Issue by JoeyT1994** [mtfishman/ITensorNetworks.jl#21]
Trying to apply rename_vertices to an ITensorNetwork does not automatically work, i.e the following error is raised:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/51231103/202816707-659b70a0-bb08-4ee8-958c-7212f8be8b47.png">

**Comment by mtfishman** [comment]
Should be fixed now in the latest version.
