### ISSUE TITLE
Current Implementation of apply() can be made more efficient

### ISSUE THREAD

**Issue by JoeyT1994** [mtfishman/ITensorNetworks.jl#39]
The current implementation of the `function ITensors.apply(o::ITensor, ψ::AbstractITensorNetwork; cutoff=nothing, maxdim=nothing, normalize=false, ortho=false)` for a two-site ITensor `o` that acts on sites `v1` and `v2` multiplies the local tensors `ψ[v1]` and `ψ[v2]` together before applying the gate and performing an SVD.

Assume chi is the dimension of all virtual bonds in `ψ`, the above multiplication operation creates a tensor with O(chi^{n}) elements where n is two less than the sum of the co-ordination numbers of v1 and v2. For a PEPS such an object will have O(chi^{6}) elements. This memory intensive process can be avoided by first performing a QR decomposition on the relevant sites and then applying the gate, i.e. (with perhaps some tag replacement to maintain consistency in the indices of  `ψ` before and after).

```
Qv1, Rv1 = factorize(ψ[v1], uniqueinds(uniqueinds(ψ[v1], ψ[v2]), inds(ψ[v1], tags ="Site")))  
Qv2, Rv2 = factorize(ψ[v2], uniqueinds(uniqueinds(ψ[v2], ψ[v1]), inds(ψ[v2], tags ="Site")))  
Rv1_new, Rv2_new = factorize(noprime(Rv1*o*Rv2), inds(Rv1); cutoff, maxdim)  
ψ[v1] = Qv1 * Rv1_new  
ψ[v2] = Qv2 * Rv2_new
```

This is what is done during full update style implementations and so should be a step that we will always want to do before applying a two-site gate.

**Comment by emstoudenmire** [comment]
This sounds like an important improvement to have. My only comment would be that it could make sense to still have a special case when the network is locally like an MPS where the QRs might be unnecessary. This special case could be detected either through just counting the number of indices, or by doing an analysis of the cost of the QR's and other operations to see which option does less computation.
