### ISSUE TITLE
Contracting Vertices and Deleting Vertices in a ITensorNetwork formed from an inner product

### ISSUE THREAD

**Issue by JoeyT1994** [mtfishman/ITensorNetworks.jl#5]
Given an ITensorNetwork formed from the inner product of two ITensorNetworks, trying to delete a vertex or contract a vertex onto another raises an error that the corresponding vertex doesn't exist.

Mininal Working Example:

```julia
using ITensors
using ITensorNetworks

dims = (2,2)
n = prod(dims)
g = named_grid(dims)

s = siteinds("S=1/2", g)

ψ_peps = ITensorNetwork(s, v -> "↑")

tn = inner(ψ_peps, sim(dag(ψ_peps), sites=[]))

display(tn[(2,1,2)])

tn = ITensors.contract(tn,  (2, 1,2) => (1, 1,2))
```
Raises the following output:

![image](https://user-images.githubusercontent.com/51231103/188969857-b543bb49-f4e6-47e0-8517-c40593731ea2.png)

The issue seems to track down to attempting to remove a vertex (using the overloaded rem_vertex! from the graphs julia package) from the inner product tensor network.

Another Minimal Working Example which raises an issue when trying to form an inner product from an ITensorNetwork which has a vertex deleted from it:

```julia
using ITensors
using ITensorNetworks
using MultiDimDictionaries
using NamedGraphs
using Graphs

dims = (2,2)
n = prod(dims)
g = named_grid(dims)

s = siteinds("S=1/2", g)

ψ_peps = ITensorNetwork(s, v -> "↑")

rem_vertex!(ψ_peps, (1,2))

display(ψ_peps)

tn = inner(ψ_peps, sim(dag(ψ_peps), sites=[]))
```
Raising the output:

![image](https://user-images.githubusercontent.com/51231103/188971413-ffdda16e-95ec-4509-af8f-ce7ee35edc11.png)

**Comment by mtfishman** [comment]
The first one seems to work fine for me, maybe some of your packages are outdated?

I'm not surprised the second one doesn't work, I don't remember testing if `rem_vertex!` works for `ITensorNetwork`s. I can take a look at getting that working.

**Comment by JoeyT1994** [comment]
I tried updating all my Julia packages but still seem to get the same issue (both on my MacOS build of ITensor and on my Linux build).

That's interesting it doesn't give you an error - I didn't have this error the first time I installed ITensorNetworks.jl but have had it on any subsequent uses of the package (despite not making any changes I can see that would cause it). 

I believe these two errors are tied together for me because my call to contract traces back to the following part of the source code (lines 234-240 in src/abstractitensornetwork.jl) :

![image](https://user-images.githubusercontent.com/51231103/189360223-5716e01d-2c44-49f3-b257-04f4a107a5e2.png)

which tries to contract by multiplying the two vertices together and then uses rem_vertex! on an itensornetwork.

Where should the line _tn = ITensors.contract(tn,  (2, 1,2) => (1, 1,2))_ trace to instead? I.e. where is your call to contract going?

**Comment by JoeyT1994** [comment]
Deleted last comment as it was wrong.

I updated the packages (and rebooted Julia to get the changes through) and this seems to have fixed the issue for now.

The contract call does seem to utilize the rem_vertex! function from graphs.jl (lines 228 in abstractitensornetwork.jl)

![image](https://user-images.githubusercontent.com/51231103/189387845-3acb8b2c-5143-41a2-8c17-4b4afd44181b.png)

but this seems to work now once the packages are all properly updated.

I will close the issue.

**Comment by mtfishman** [comment]
Glad to hear these are fixed for you now.

I just made a few updates to the packages [MultiDimDictionaries.jl](https://github.com/mtfishman/MultiDimDictionaries.jl), [NamedGraphs.jl](https://github.com/mtfishman/NamedGraphs.jl), [DataGraphs.jl](https://github.com/mtfishman/DataGraphs.jl), that should have fixed the second issue you were seeing. The first issue you were seeing may have relied on a local change I made to [MultiDimDictionaries.jl](https://github.com/mtfishman/MultiDimDictionaries.jl) which I forgot to push.

The second issue was actually caused by a bug in the [Dictionaries.jl](https://github.com/andyferris/Dictionaries.jl) package when deleting a key from a `Dictionary`:
```julia
julia> using Dictionaries

julia> d = Dictionary{Tuple}([(1, 1), (2, 1), (1, 2), (2, 2)], [1, 2, 3, 4])
4-element Dictionary{Tuple, Int64}
 (1, 1) │ 1
 (2, 1) │ 2
 (1, 2) │ 3
 (2, 2) │ 4

julia> delete!(d, (1, 1))
3-element Dictionary{Tuple, Int64}
 (2, 1) │ 2
 (1, 2) │ 3
 (2, 2) │ 4

julia> deepcopy(d)
ERROR: UndefRefError: access to undefined reference
Stacktrace:
  [1] getindex
    @ ./array.jl:924 [inlined]
  [2] iterate (repeats 2 times)
    @ ./array.jl:898 [inlined]
  [3] iterate
    @ ./generator.jl:44 [inlined]
  [4] _collect(c::Vector{Tuple}, itr::Base.Generator{Vector{Tuple}, Dictionaries.var"#43#44"}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:807
  [5] collect_similar
    @ ./array.jl:716 [inlined]
  [6] map
    @ ./abstractarray.jl:2933 [inlined]
  [7] Indices{Tuple}(values::Vector{Tuple})
    @ Dictionaries ~/.julia/packages/Dictionaries/8bcEH/src/Indices.jl:89
  [8] deepcopy_internal(ind::Indices{Tuple}, id::IdDict{Any, Any})
    @ Dictionaries ~/.julia/packages/Dictionaries/8bcEH/src/Indices.jl:188
  [9] deepcopy_internal(x::Any, stackdict::IdDict{Any, Any})
    @ Base ./deepcopy.jl:76
 [10] deepcopy(x::Dictionary{Tuple, Int64})
    @ Base ./deepcopy.jl:26
 [11] top-level scope
    @ REPL[6]:1
```
The `Dictionary` type is being used to store metadata for the tensor networks. I circumvented that issue by avoiding using `deepcopy`, I'll raise this as an issue in Dictionaries.jl.

**Comment by mtfishman** [comment]
By the way, if you use [Revise.jl](https://github.com/timholy/Revise.jl) you should be able to make changes to packages without having to reboot Julia.

**Comment by JoeyT1994** [comment]
Okay great, thanks for looking into it and fixing these issues! Thanks for the tip about Revise.jl too, that will be useful.
