### ISSUE TITLE
Constructing a Tree Tensor Network Operator doesn't work on integer labelled vertices

### ISSUE THREAD

**Issue by JoeyT1994** [mtfishman/ITensorNetworks.jl#51]
The following code:

```
using ITensors
using ITensorNetworks
using NamedGraphs
using Graphs

n =2
g = NamedGraph(path_graph(n))
s = siteinds("S=1/2", g)

ops = OpSum()
ops += 1.0, "Sz", 1, "Sz", 2

@show TTN(ops, s)
```

produces the error:

![image](https://user-images.githubusercontent.com/51231103/213819078-38ab89b7-118e-40ad-90f9-0f2377ea46e7.png)

Which goes away if one names the vertices of `g` as tuples instead of Integers.

Is this unexpected? Or is `TTN()` only defined for `IndexNetworks` labelled with tuples?

**Comment by mtfishman** [comment]
I noticed this issue as well, it should be fixed by https://github.com/mtfishman/DataGraphs.jl/pull/15.
