### ISSUE TITLE
`OpSum` to `TTN` broken for multiple on-site operators

### ISSUE THREAD

**Issue by JoeyT1994** [mtfishman/ITensorNetworks.jl#62]
Was playing around with `TTN()` and found the following code

```
using NamedGraphs
using ITensorNetworks
using ITensors

grid_dims = (2, 1)
g = named_grid(grid_dims)
s = siteinds("S=1/2", g)

os = OpSum()
os += 1.0, "Sx", (1,1)
os += 0.0, "Sy", (1,1)
H = TTN(os, s)

@show H[(1,1)]

os = OpSum()
os += 1.0, "Sx", (1,1)
H = TTN(os, s)

@show H[(1,1)]

```

realizes two different `TTN`s which contract to different values when applied to some `ψ`. Specifically the output of the above is:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/51231103/216791623-299b1d1d-8324-4167-b627-54a274b833e2.png">.

This is despite the fact the `TTN`s should be identical (up to arbitrary index ids). In general, there appears to be something strange happening with the `"Sx"` operator for spin half systems --- when one adds mixes in other terms with a local `"Sx"` field the wrong `TTN` appears to get constructed.

**Comment by mtfishman** [comment]
If you contract the TTN in both cases (`H[1, 1] * H[2, 1]`) does it give the correct Hamiltonian?

**Comment by mtfishman** [comment]
Does it create the correct Hamiltonian for:
```julia
os = OpSum()
os += 1.0, "Sx", (1,1)
os += 1.0, "Sy", (1,1)
H = TTN(os, s)
```
? If not then it is probably an issue with having multiple on-site operators.

**Comment by JoeyT1994** [comment]
I believe it returns `KroneckerProduct(Sy, IdentityMatrix)` in this case and ignore the `Sx` part.
I agree this would make sense and be consistent with what I have seen (it does not have a problem when you mix multiple two-site operators)

**Comment by mtfishman** [comment]
Ok, that's helpful.

@leburgel or @emstoudenmire could you take a look at this?
